# Generated by Django 5.1.3 on 2024-11-15 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True, null=True)),
                ('name', models.CharField(db_column='tx_name', max_length=50)),
            ],
            options={
                'db_table': 'exercise_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True, null=True)),
                ('name', models.CharField(db_column='tx_name', max_length=70)),
            ],
            options={
                'db_table': 'muscle_group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True, null=True)),
                ('name', models.CharField(db_column='tx_name', max_length=70)),
                ('category', models.ForeignKey(db_column='tx_category', on_delete=django.db.models.deletion.CASCADE, to='core.exercisecategory')),
                ('muscle_group', models.ForeignKey(db_column='tx_muscle_group', on_delete=django.db.models.deletion.CASCADE, to='core.musclegroup')),
            ],
            options={
                'db_table': 'exercise',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True, null=True)),
                ('name', models.CharField(db_column='tx_name', default='')),
                ('age', models.IntegerField(db_column='nb_age')),
                ('weight', models.FloatField(db_column='nb_weight')),
                ('height', models.FloatField(db_column='nb_height')),
                ('login', models.ForeignKey(db_column='tx_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True, null=True)),
                ('repetitions', models.IntegerField(db_column='nb_repetitions')),
                ('series', models.IntegerField(db_column='nb_series')),
                ('rest_time', models.DurationField(db_column='nb_rest_time')),
                ('exercise', models.ForeignKey(db_column='tx_exercise', on_delete=django.db.models.deletion.CASCADE, to='core.exercise')),
                ('user_profile', models.ForeignKey(db_column='tx_user', on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
            options={
                'db_table': 'training',
                'managed': True,
            },
        ),
    ]
