# Generated by Django 5.1.3 on 2024-11-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'managed': True, 'verbose_name': 'Exercício', 'verbose_name_plural': 'Exercícios'},
        ),
        migrations.AlterModelOptions(
            name='musclegroup',
            options={'managed': True, 'verbose_name': 'Grupo muscular', 'verbose_name_plural': 'Grupos musculares'},
        ),
        migrations.AddField(
            model_name='training',
            name='name',
            field=models.CharField(db_column='tx_name', default='sem nome', max_length=70),
        ),
        migrations.DeleteModel(
            name='ExerciseCategory',
        ),
    ]
