# Generated by Django 5.1.3 on 2024-11-23 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userprofile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='training',
            name='repetitions',
        ),
        migrations.RemoveField(
            model_name='training',
            name='rest_time',
        ),
        migrations.RemoveField(
            model_name='training',
            name='series',
        ),
        migrations.CreateModel(
            name='TrainingExercise',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True, null=True)),
                ('repetitions', models.IntegerField(db_column='nb_repetitions')),
                ('series', models.IntegerField(db_column='nb_series')),
                ('rest_time', models.DurationField(db_column='nb_rest_time')),
                ('exercise', models.ForeignKey(db_column='tx_exercise', on_delete=django.db.models.deletion.CASCADE, to='core.exercise')),
                ('training', models.ForeignKey(db_column='tx_training', on_delete=django.db.models.deletion.CASCADE, to='core.training')),
            ],
            options={
                'db_table': 'training_exercise',
                'managed': True,
            },
        ),
    ]
