# Generated by Django 5.1.3 on 2024-11-24 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_training_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='user_profile',
        ),
    ]
