# Generated by Django 5.1.3 on 2024-11-30 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_training_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True, null=True)),
                ('description', models.CharField(db_column='tx_name', max_length=300)),
                ('total_kcal', models.FloatField(db_column='nb_total_kcal')),
            ],
            options={
                'verbose_name': 'Comida',
                'verbose_name_plural': 'Comidas',
                'db_table': 'food',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True, null=True)),
                ('date', models.DateField(db_column='tx_date')),
                ('meal_type', models.IntegerField(choices=[(1, 'Café da manhã'), (2, 'Lanche da manhã'), (3, 'Almoço'), (4, 'Lanche da tarde'), (5, 'Jantar'), (6, 'Ceia'), (7, 'Pré-teino'), (8, 'Pós-treino'), (9, 'Lanche noturno'), (10, 'Brunch')])),
                ('user', models.ForeignKey(db_column='nb_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refeição',
                'verbose_name_plural': 'Refeições',
                'db_table': 'meal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MealFood',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True, null=True)),
                ('unit', models.IntegerField(choices=[(1, 'mL'), (2, 'g'), (3, 'un')])),
                ('value', models.FloatField(db_column='nb_value')),
                ('food', models.ForeignKey(db_column='nb_food', on_delete=django.db.models.deletion.CASCADE, to='core.food')),
                ('meal', models.ForeignKey(db_column='nb_meal', on_delete=django.db.models.deletion.CASCADE, to='core.meal')),
            ],
            options={
                'db_table': 'meal_food',
            },
        ),
    ]
