# Generated by Django 5.1.3 on 2024-12-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_food_meal_mealfood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealfood',
            name='unit',
        ),
        migrations.AddField(
            model_name='food',
            name='unit',
            field=models.IntegerField(choices=[(1, 'mL'), (2, 'g'), (3, 'un')], default=2),
        ),
        migrations.AddField(
            model_name='food',
            name='value',
            field=models.FloatField(db_column='nb_value', default=0),
        ),
    ]
