# Generated by Django 5.1.3 on 2024-12-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_unaccent'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='date',
            field=models.DateField(db_column='date', default=None),
        ),
    ]
